export const initialState = {
  view: 'home',
  currentDate: new Date(),
  tasks: [],
  events: [],
  meals: [
    { day: 'Mon', meal: '' },
    { day: 'Tue', meal: '' },
    { day: 'Wed', meal: '' },
    { day: 'Thu', meal: '' },
    { day: 'Fri', meal: '' },
    { day: 'Sat', meal: '' },
    { day: 'Sun', meal: '' },
  ],
  groceries: [],
  lists: [],
  nextTaskId: 1,
  nextListId: 1,
  nextNotifId: 1,
  nextRecipeId: 1,
  nextEventId: 1,
  nextChoreId: 1,
  nextRewardId: 1,
  nextRoutineId: 1,
  nextBillId: 1,
  editingMealIdx: null,
  selectedRecipeId: null,
  recipes: [],
  profiles: [],
  notifications: [],
  budget: {
    monthly: 0,
    categories: [],
    transactions: [],
  },
  chores: [],
  rewards: [],
  routines: [],
  bills: [],
};
