export const initialState = {
  view: 'home',
  currentDate: new Date(),
  calendarViewMode: 'month', // 'month', 'week', or 'day'
  budgetTab: 'budget',
  budgetViewMonth: new Date(),
  tasks: [],
  events: [], // Event structure: {id, title, date, time, person, category, emoji, personId}
  meals: [
    { day: 'Mon', meal: '' },
    { day: 'Tue', meal: '' },
    { day: 'Wed', meal: '' },
    { day: 'Thu', meal: '' },
    { day: 'Fri', meal: '' },
    { day: 'Sat', meal: '' },
    { day: 'Sun', meal: '' },
  ],
  groceries: [],
  lists: [],
  nextTaskId: 1,
  nextListId: 1,
  nextNotifId: 1,
  nextRecipeId: 1,
  nextEventId: 1,
  nextChoreId: 1,
  nextRewardId: 1,
  nextRoutineId: 1,
  nextBillId: 1,
  nextTransactionId: 1,
  nextCategoryId: 1,
  nextProfileId: 1,
  editingMealIdx: null,
  selectedRecipeId: null,
  recipes: [],
  profiles: [],
  notifications: [],
  budget: {
    periodAmount: 0,
    periodType: 'monthly',
    categories: [],
    transactions: [],
  },
  chores: [],
  rewards: [],
  routines: [],
  bills: [],
};
